// Package mocks provides autogenerated mock implementations for interfaces used in the application.
// These mocks are generated using the mockery tool and are intended for use in unit tests.
package mocks
