version: "3"

tasks:
  lint:
    desc: Run linters using golangci-lint
    cmds:
      - golangci-lint run --config .golangci.yml
    silent: true
  build:
    desc: build project
    dir: cmd/shortener
    cmds:
      - go build -o shortener
      - echo "Doner"
    silent: true
  run:
    desc: run project
    dir: cmd/shortener
    cmds:
      - go run main.go -f="db.json" #-d="postgres://postgres:postgres@localhost:5432/practicum?sslmode=disable"
    silent: true

  test:
    desc: build and run tests
    deps:
      - build
    cmds:
      - ./shortenertest -test.v -test.run=^TestIteration1$ -binary-path=cmd/shortener/shortener
      - ./shortenertest -test.v -test.run=^TestIteration2$ -source-path="."
      - ./shortenertest -test.v -test.run=^TestIteration3$ -source-path="."
      - ./shortenertest -test.v -test.run=^TestIteration4$ -binary-path=cmd/shortener/shortener -server-port=8080
      - ./shortenertest -test.v -test.run=^TestIteration5$ -binary-path=cmd/shortener/shortener -server-port=8080
      - ./shortenertest -test.v -test.run=^TestIteration6$ -source-path="."
      - ./shortenertest -test.v -test.run=^TestIteration7$ -binary-path=cmd/shortener/shortener -source-path="."
      - ./shortenertest -test.v -test.run=^TestIteration8$ -binary-path=cmd/shortener/shortener
      - ./shortenertest -test.v -test.run=^TestIteration9$ -binary-path=cmd/shortener/shortener -source-path="." -file-storage-path="db.json"
      - ./shortenertest -test.v -test.run=^TestIteration10$ -binary-path=cmd/shortener/shortener -source-path="." -database-dsn="postgres://postgres:postgres@localhost:5432/practicum?sslmode=disable"
      - ./shortenertest -test.v -test.run=^TestIteration11$ -binary-path=cmd/shortener/shortener -database-dsn="postgres://postgres:postgres@localhost:5432/practicum?sslmode=disable"
      - ./shortenertest -test.v -test.run=^TestIteration12$ -binary-path=cmd/shortener/shortener -database-dsn="postgres://postgres:postgres@localhost:5432/practicum?sslmode=disable"
      - ./shortenertest -test.v -test.run=^TestIteration13$ -binary-path=cmd/shortener/shortener -database-dsn="postgres://postgres:postgres@localhost:5432/practicum?sslmode=disable"
      - ./shortenertest -test.v -test.run=^TestIteration14$ -binary-path=cmd/shortener/shortener -database-dsn="postgres://postgres:postgres@localhost:5432/practicum?sslmode=disable"
      - ./shortenertest -test.v -test.run=^TestIteration15$ -binary-path=cmd/shortener/shortener -database-dsn="postgres://postgres:postgres@localhost:5432/practicum?sslmode=disable"
