// proto Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/shortugo.proto

//go:build !protoopaque

package proto

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type URLPair struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	CorrelationId *string                `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId" json:"correlation_id,omitempty"`
	OriginalUrl   *string                `protobuf:"bytes,2,opt,name=original_url,json=originalUrl" json:"original_url,omitempty"`
	ShortUrl      *string                `protobuf:"bytes,3,opt,name=short_url,json=shortUrl" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLPair) Reset() {
	*x = URLPair{}
	mi := &file_proto_shortugo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLPair) ProtoMessage() {}

func (x *URLPair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *URLPair) GetCorrelationId() string {
	if x != nil && x.CorrelationId != nil {
		return *x.CorrelationId
	}
	return ""
}

func (x *URLPair) GetOriginalUrl() string {
	if x != nil && x.OriginalUrl != nil {
		return *x.OriginalUrl
	}
	return ""
}

func (x *URLPair) GetShortUrl() string {
	if x != nil && x.ShortUrl != nil {
		return *x.ShortUrl
	}
	return ""
}

func (x *URLPair) SetCorrelationId(v string) {
	x.CorrelationId = &v
}

func (x *URLPair) SetOriginalUrl(v string) {
	x.OriginalUrl = &v
}

func (x *URLPair) SetShortUrl(v string) {
	x.ShortUrl = &v
}

func (x *URLPair) HasCorrelationId() bool {
	if x == nil {
		return false
	}
	return x.CorrelationId != nil
}

func (x *URLPair) HasOriginalUrl() bool {
	if x == nil {
		return false
	}
	return x.OriginalUrl != nil
}

func (x *URLPair) HasShortUrl() bool {
	if x == nil {
		return false
	}
	return x.ShortUrl != nil
}

func (x *URLPair) ClearCorrelationId() {
	x.CorrelationId = nil
}

func (x *URLPair) ClearOriginalUrl() {
	x.OriginalUrl = nil
}

func (x *URLPair) ClearShortUrl() {
	x.ShortUrl = nil
}

type URLPair_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CorrelationId *string
	OriginalUrl   *string
	ShortUrl      *string
}

func (b0 URLPair_builder) Build() *URLPair {
	m0 := &URLPair{}
	b, x := &b0, m0
	_, _ = b, x
	x.CorrelationId = b.CorrelationId
	x.OriginalUrl = b.OriginalUrl
	x.ShortUrl = b.ShortUrl
	return m0
}

type ShortenRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	OriginalUrl   *string                `protobuf:"bytes,1,opt,name=original_url,json=originalUrl" json:"original_url,omitempty"`
	UserId        *string                `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenRequest) Reset() {
	*x = ShortenRequest{}
	mi := &file_proto_shortugo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenRequest) ProtoMessage() {}

func (x *ShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ShortenRequest) GetOriginalUrl() string {
	if x != nil && x.OriginalUrl != nil {
		return *x.OriginalUrl
	}
	return ""
}

func (x *ShortenRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *ShortenRequest) SetOriginalUrl(v string) {
	x.OriginalUrl = &v
}

func (x *ShortenRequest) SetUserId(v string) {
	x.UserId = &v
}

func (x *ShortenRequest) HasOriginalUrl() bool {
	if x == nil {
		return false
	}
	return x.OriginalUrl != nil
}

func (x *ShortenRequest) HasUserId() bool {
	if x == nil {
		return false
	}
	return x.UserId != nil
}

func (x *ShortenRequest) ClearOriginalUrl() {
	x.OriginalUrl = nil
}

func (x *ShortenRequest) ClearUserId() {
	x.UserId = nil
}

type ShortenRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OriginalUrl *string
	UserId      *string
}

func (b0 ShortenRequest_builder) Build() *ShortenRequest {
	m0 := &ShortenRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.OriginalUrl = b.OriginalUrl
	x.UserId = b.UserId
	return m0
}

type ShortenResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	ShortUrl      *string                `protobuf:"bytes,1,opt,name=short_url,json=shortUrl" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenResponse) Reset() {
	*x = ShortenResponse{}
	mi := &file_proto_shortugo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenResponse) ProtoMessage() {}

func (x *ShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ShortenResponse) GetShortUrl() string {
	if x != nil && x.ShortUrl != nil {
		return *x.ShortUrl
	}
	return ""
}

func (x *ShortenResponse) SetShortUrl(v string) {
	x.ShortUrl = &v
}

func (x *ShortenResponse) HasShortUrl() bool {
	if x == nil {
		return false
	}
	return x.ShortUrl != nil
}

func (x *ShortenResponse) ClearShortUrl() {
	x.ShortUrl = nil
}

type ShortenResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ShortUrl *string
}

func (b0 ShortenResponse_builder) Build() *ShortenResponse {
	m0 := &ShortenResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.ShortUrl = b.ShortUrl
	return m0
}

type ExpandRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	ShortUrlId    *string                `protobuf:"bytes,1,opt,name=short_url_id,json=shortUrlId" json:"short_url_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandRequest) Reset() {
	*x = ExpandRequest{}
	mi := &file_proto_shortugo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandRequest) ProtoMessage() {}

func (x *ExpandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExpandRequest) GetShortUrlId() string {
	if x != nil && x.ShortUrlId != nil {
		return *x.ShortUrlId
	}
	return ""
}

func (x *ExpandRequest) SetShortUrlId(v string) {
	x.ShortUrlId = &v
}

func (x *ExpandRequest) HasShortUrlId() bool {
	if x == nil {
		return false
	}
	return x.ShortUrlId != nil
}

func (x *ExpandRequest) ClearShortUrlId() {
	x.ShortUrlId = nil
}

type ExpandRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ShortUrlId *string
}

func (b0 ExpandRequest_builder) Build() *ExpandRequest {
	m0 := &ExpandRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.ShortUrlId = b.ShortUrlId
	return m0
}

type ExpandResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	OriginalUrl   *string                `protobuf:"bytes,1,opt,name=original_url,json=originalUrl" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandResponse) Reset() {
	*x = ExpandResponse{}
	mi := &file_proto_shortugo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandResponse) ProtoMessage() {}

func (x *ExpandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExpandResponse) GetOriginalUrl() string {
	if x != nil && x.OriginalUrl != nil {
		return *x.OriginalUrl
	}
	return ""
}

func (x *ExpandResponse) SetOriginalUrl(v string) {
	x.OriginalUrl = &v
}

func (x *ExpandResponse) HasOriginalUrl() bool {
	if x == nil {
		return false
	}
	return x.OriginalUrl != nil
}

func (x *ExpandResponse) ClearOriginalUrl() {
	x.OriginalUrl = nil
}

type ExpandResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OriginalUrl *string
}

func (b0 ExpandResponse_builder) Build() *ExpandResponse {
	m0 := &ExpandResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.OriginalUrl = b.OriginalUrl
	return m0
}

type ShortenBatchRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	UserId        *string                `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Urls          []*URLPair             `protobuf:"bytes,2,rep,name=urls" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchRequest) Reset() {
	*x = ShortenBatchRequest{}
	mi := &file_proto_shortugo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchRequest) ProtoMessage() {}

func (x *ShortenBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ShortenBatchRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *ShortenBatchRequest) GetUrls() []*URLPair {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *ShortenBatchRequest) SetUserId(v string) {
	x.UserId = &v
}

func (x *ShortenBatchRequest) SetUrls(v []*URLPair) {
	x.Urls = v
}

func (x *ShortenBatchRequest) HasUserId() bool {
	if x == nil {
		return false
	}
	return x.UserId != nil
}

func (x *ShortenBatchRequest) ClearUserId() {
	x.UserId = nil
}

type ShortenBatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId *string
	Urls   []*URLPair
}

func (b0 ShortenBatchRequest_builder) Build() *ShortenBatchRequest {
	m0 := &ShortenBatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.UserId = b.UserId
	x.Urls = b.Urls
	return m0
}

type ShortenBatchResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Results       []*URLPair             `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchResponse) Reset() {
	*x = ShortenBatchResponse{}
	mi := &file_proto_shortugo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchResponse) ProtoMessage() {}

func (x *ShortenBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ShortenBatchResponse) GetResults() []*URLPair {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ShortenBatchResponse) SetResults(v []*URLPair) {
	x.Results = v
}

type ShortenBatchResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Results []*URLPair
}

func (b0 ShortenBatchResponse_builder) Build() *ShortenBatchResponse {
	m0 := &ShortenBatchResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Results = b.Results
	return m0
}

type ListUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	UserId        *string                `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserURLsRequest) Reset() {
	*x = ListUserURLsRequest{}
	mi := &file_proto_shortugo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserURLsRequest) ProtoMessage() {}

func (x *ListUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListUserURLsRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *ListUserURLsRequest) SetUserId(v string) {
	x.UserId = &v
}

func (x *ListUserURLsRequest) HasUserId() bool {
	if x == nil {
		return false
	}
	return x.UserId != nil
}

func (x *ListUserURLsRequest) ClearUserId() {
	x.UserId = nil
}

type ListUserURLsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId *string
}

func (b0 ListUserURLsRequest_builder) Build() *ListUserURLsRequest {
	m0 := &ListUserURLsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.UserId = b.UserId
	return m0
}

type ListUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Urls          []*URLPair             `protobuf:"bytes,1,rep,name=urls" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserURLsResponse) Reset() {
	*x = ListUserURLsResponse{}
	mi := &file_proto_shortugo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserURLsResponse) ProtoMessage() {}

func (x *ListUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListUserURLsResponse) GetUrls() []*URLPair {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *ListUserURLsResponse) SetUrls(v []*URLPair) {
	x.Urls = v
}

type ListUserURLsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Urls []*URLPair
}

func (b0 ListUserURLsResponse_builder) Build() *ListUserURLsResponse {
	m0 := &ListUserURLsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Urls = b.Urls
	return m0
}

type DeleteUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	UserId        *string                `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ShortUrlIds   []string               `protobuf:"bytes,2,rep,name=short_url_ids,json=shortUrlIds" json:"short_url_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLsRequest) Reset() {
	*x = DeleteUserURLsRequest{}
	mi := &file_proto_shortugo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsRequest) ProtoMessage() {}

func (x *DeleteUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteUserURLsRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *DeleteUserURLsRequest) GetShortUrlIds() []string {
	if x != nil {
		return x.ShortUrlIds
	}
	return nil
}

func (x *DeleteUserURLsRequest) SetUserId(v string) {
	x.UserId = &v
}

func (x *DeleteUserURLsRequest) SetShortUrlIds(v []string) {
	x.ShortUrlIds = v
}

func (x *DeleteUserURLsRequest) HasUserId() bool {
	if x == nil {
		return false
	}
	return x.UserId != nil
}

func (x *DeleteUserURLsRequest) ClearUserId() {
	x.UserId = nil
}

type DeleteUserURLsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId      *string
	ShortUrlIds []string
}

func (b0 DeleteUserURLsRequest_builder) Build() *DeleteUserURLsRequest {
	m0 := &DeleteUserURLsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.UserId = b.UserId
	x.ShortUrlIds = b.ShortUrlIds
	return m0
}

type DeleteUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Success       *bool                  `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLsResponse) Reset() {
	*x = DeleteUserURLsResponse{}
	mi := &file_proto_shortugo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsResponse) ProtoMessage() {}

func (x *DeleteUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteUserURLsResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *DeleteUserURLsResponse) SetSuccess(v bool) {
	x.Success = &v
}

func (x *DeleteUserURLsResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return x.Success != nil
}

func (x *DeleteUserURLsResponse) ClearSuccess() {
	x.Success = nil
}

type DeleteUserURLsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Success *bool
}

func (b0 DeleteUserURLsResponse_builder) Build() *DeleteUserURLsResponse {
	m0 := &DeleteUserURLsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Success = b.Success
	return m0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_shortugo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type HealthCheckRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 HealthCheckRequest_builder) Build() *HealthCheckRequest {
	m0 := &HealthCheckRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Status        *string                `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_shortugo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *HealthCheckResponse) SetStatus(v string) {
	x.Status = &v
}

func (x *HealthCheckResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *HealthCheckResponse) ClearStatus() {
	x.Status = nil
}

type HealthCheckResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status *string
}

func (b0 HealthCheckResponse_builder) Build() *HealthCheckResponse {
	m0 := &HealthCheckResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Status = b.Status
	return m0
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_shortugo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PingRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 PingRequest_builder) Build() *PingRequest {
	m0 := &PingRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Status        *string                `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_shortugo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PingResponse) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *PingResponse) SetStatus(v string) {
	x.Status = &v
}

func (x *PingResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *PingResponse) ClearStatus() {
	x.Status = nil
}

type PingResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status *string
}

func (b0 PingResponse_builder) Build() *PingResponse {
	m0 := &PingResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Status = b.Status
	return m0
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Ip            *string                `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"` // IP address of the client, used for trusted subnet validation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_shortugo_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StatsRequest) GetIp() string {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return ""
}

func (x *StatsRequest) SetIp(v string) {
	x.Ip = &v
}

func (x *StatsRequest) HasIp() bool {
	if x == nil {
		return false
	}
	return x.Ip != nil
}

func (x *StatsRequest) ClearIp() {
	x.Ip = nil
}

type StatsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ip *string
}

func (b0 StatsRequest_builder) Build() *StatsRequest {
	m0 := &StatsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Ip = b.Ip
	return m0
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	UrlCount      *int64                 `protobuf:"varint,1,opt,name=url_count,json=urlCount" json:"url_count,omitempty"`
	UserCount     *int64                 `protobuf:"varint,2,opt,name=user_count,json=userCount" json:"user_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_shortugo_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StatsResponse) GetUrlCount() int64 {
	if x != nil && x.UrlCount != nil {
		return *x.UrlCount
	}
	return 0
}

func (x *StatsResponse) GetUserCount() int64 {
	if x != nil && x.UserCount != nil {
		return *x.UserCount
	}
	return 0
}

func (x *StatsResponse) SetUrlCount(v int64) {
	x.UrlCount = &v
}

func (x *StatsResponse) SetUserCount(v int64) {
	x.UserCount = &v
}

func (x *StatsResponse) HasUrlCount() bool {
	if x == nil {
		return false
	}
	return x.UrlCount != nil
}

func (x *StatsResponse) HasUserCount() bool {
	if x == nil {
		return false
	}
	return x.UserCount != nil
}

func (x *StatsResponse) ClearUrlCount() {
	x.UrlCount = nil
}

func (x *StatsResponse) ClearUserCount() {
	x.UserCount = nil
}

type StatsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UrlCount  *int64
	UserCount *int64
}

func (b0 StatsResponse_builder) Build() *StatsResponse {
	m0 := &StatsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.UrlCount = b.UrlCount
	x.UserCount = b.UserCount
	return m0
}

var File_proto_shortugo_proto protoreflect.FileDescriptor

const file_proto_shortugo_proto_rawDesc = "" +
	"\n" +
	"\x14proto/shortugo.proto\x12\bshortugo\x1a!google/protobuf/go_features.proto\"p\n" +
	"\aURLPair\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\x12\x1b\n" +
	"\tshort_url\x18\x03 \x01(\tR\bshortUrl\"L\n" +
	"\x0eShortenRequest\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\".\n" +
	"\x0fShortenResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"1\n" +
	"\rExpandRequest\x12 \n" +
	"\fshort_url_id\x18\x01 \x01(\tR\n" +
	"shortUrlId\"3\n" +
	"\x0eExpandResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"U\n" +
	"\x13ShortenBatchRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x04urls\x18\x02 \x03(\v2\x11.shortugo.URLPairR\x04urls\"C\n" +
	"\x14ShortenBatchResponse\x12+\n" +
	"\aresults\x18\x01 \x03(\v2\x11.shortugo.URLPairR\aresults\".\n" +
	"\x13ListUserURLsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"=\n" +
	"\x14ListUserURLsResponse\x12%\n" +
	"\x04urls\x18\x01 \x03(\v2\x11.shortugo.URLPairR\x04urls\"T\n" +
	"\x15DeleteUserURLsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\"\n" +
	"\rshort_url_ids\x18\x02 \x03(\tR\vshortUrlIds\"2\n" +
	"\x16DeleteUserURLsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\r\n" +
	"\vPingRequest\"&\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x1e\n" +
	"\fStatsRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"K\n" +
	"\rStatsResponse\x12\x1b\n" +
	"\turl_count\x18\x01 \x01(\x03R\burlCount\x12\x1d\n" +
	"\n" +
	"user_count\x18\x02 \x01(\x03R\tuserCount2\xff\x04\n" +
	"\fURLShortener\x12>\n" +
	"\aShorten\x12\x18.shortugo.ShortenRequest\x1a\x19.shortugo.ShortenResponse\x12B\n" +
	"\vShortenJSON\x12\x18.shortugo.ShortenRequest\x1a\x19.shortugo.ShortenResponse\x12M\n" +
	"\fShortenBatch\x12\x1d.shortugo.ShortenBatchRequest\x1a\x1e.shortugo.ShortenBatchResponse\x12;\n" +
	"\x06Expand\x12\x17.shortugo.ExpandRequest\x1a\x18.shortugo.ExpandResponse\x12M\n" +
	"\fListUserURLs\x12\x1d.shortugo.ListUserURLsRequest\x1a\x1e.shortugo.ListUserURLsResponse\x12S\n" +
	"\x0eDeleteUserURLs\x12\x1f.shortugo.DeleteUserURLsRequest\x1a .shortugo.DeleteUserURLsResponse\x12J\n" +
	"\vHealthCheck\x12\x1c.shortugo.HealthCheckRequest\x1a\x1d.shortugo.HealthCheckResponse\x125\n" +
	"\x04Ping\x12\x15.shortugo.PingRequest\x1a\x16.shortugo.PingResponse\x128\n" +
	"\x05Stats\x12\x16.shortugo.StatsRequest\x1a\x17.shortugo.StatsResponseB\x16Z\f/proto;proto\x92\x03\x05\xd2>\x02\x10\x02b\beditionsp\xe8\a"

var file_proto_shortugo_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_shortugo_proto_goTypes = []any{
	(*URLPair)(nil),                // 0: shortugo.URLPair
	(*ShortenRequest)(nil),         // 1: shortugo.ShortenRequest
	(*ShortenResponse)(nil),        // 2: shortugo.ShortenResponse
	(*ExpandRequest)(nil),          // 3: shortugo.ExpandRequest
	(*ExpandResponse)(nil),         // 4: shortugo.ExpandResponse
	(*ShortenBatchRequest)(nil),    // 5: shortugo.ShortenBatchRequest
	(*ShortenBatchResponse)(nil),   // 6: shortugo.ShortenBatchResponse
	(*ListUserURLsRequest)(nil),    // 7: shortugo.ListUserURLsRequest
	(*ListUserURLsResponse)(nil),   // 8: shortugo.ListUserURLsResponse
	(*DeleteUserURLsRequest)(nil),  // 9: shortugo.DeleteUserURLsRequest
	(*DeleteUserURLsResponse)(nil), // 10: shortugo.DeleteUserURLsResponse
	(*HealthCheckRequest)(nil),     // 11: shortugo.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 12: shortugo.HealthCheckResponse
	(*PingRequest)(nil),            // 13: shortugo.PingRequest
	(*PingResponse)(nil),           // 14: shortugo.PingResponse
	(*StatsRequest)(nil),           // 15: shortugo.StatsRequest
	(*StatsResponse)(nil),          // 16: shortugo.StatsResponse
}
var file_proto_shortugo_proto_depIdxs = []int32{
	0,  // 0: shortugo.ShortenBatchRequest.urls:type_name -> shortugo.URLPair
	0,  // 1: shortugo.ShortenBatchResponse.results:type_name -> shortugo.URLPair
	0,  // 2: shortugo.ListUserURLsResponse.urls:type_name -> shortugo.URLPair
	1,  // 3: shortugo.URLShortener.Shorten:input_type -> shortugo.ShortenRequest
	1,  // 4: shortugo.URLShortener.ShortenJSON:input_type -> shortugo.ShortenRequest
	5,  // 5: shortugo.URLShortener.ShortenBatch:input_type -> shortugo.ShortenBatchRequest
	3,  // 6: shortugo.URLShortener.Expand:input_type -> shortugo.ExpandRequest
	7,  // 7: shortugo.URLShortener.ListUserURLs:input_type -> shortugo.ListUserURLsRequest
	9,  // 8: shortugo.URLShortener.DeleteUserURLs:input_type -> shortugo.DeleteUserURLsRequest
	11, // 9: shortugo.URLShortener.HealthCheck:input_type -> shortugo.HealthCheckRequest
	13, // 10: shortugo.URLShortener.Ping:input_type -> shortugo.PingRequest
	15, // 11: shortugo.URLShortener.Stats:input_type -> shortugo.StatsRequest
	2,  // 12: shortugo.URLShortener.Shorten:output_type -> shortugo.ShortenResponse
	2,  // 13: shortugo.URLShortener.ShortenJSON:output_type -> shortugo.ShortenResponse
	6,  // 14: shortugo.URLShortener.ShortenBatch:output_type -> shortugo.ShortenBatchResponse
	4,  // 15: shortugo.URLShortener.Expand:output_type -> shortugo.ExpandResponse
	8,  // 16: shortugo.URLShortener.ListUserURLs:output_type -> shortugo.ListUserURLsResponse
	10, // 17: shortugo.URLShortener.DeleteUserURLs:output_type -> shortugo.DeleteUserURLsResponse
	12, // 18: shortugo.URLShortener.HealthCheck:output_type -> shortugo.HealthCheckResponse
	14, // 19: shortugo.URLShortener.Ping:output_type -> shortugo.PingResponse
	16, // 20: shortugo.URLShortener.Stats:output_type -> shortugo.StatsResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_shortugo_proto_init() }
func file_proto_shortugo_proto_init() {
	if File_proto_shortugo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shortugo_proto_rawDesc), len(file_proto_shortugo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shortugo_proto_goTypes,
		DependencyIndexes: file_proto_shortugo_proto_depIdxs,
		MessageInfos:      file_proto_shortugo_proto_msgTypes,
	}.Build()
	File_proto_shortugo_proto = out.File
	file_proto_shortugo_proto_goTypes = nil
	file_proto_shortugo_proto_depIdxs = nil
}
