// Package proto
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
//
//	protoc-gen-go v1.36.6
//	protoc        v3.19.6
//
// source: proto/shortugo.proto
package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type URLPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,3,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLPair) Reset() {
	*x = URLPair{}
	mi := &file_proto_shortugo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLPair) ProtoMessage() {}

func (x *URLPair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLPair.ProtoReflect.Descriptor instead.
func (*URLPair) Descriptor() ([]byte, []int) {
	return file_proto_shortugo_proto_rawDescGZIP(), []int{0}
}

func (x *URLPair) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *URLPair) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *URLPair) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type ShortenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenRequest) Reset() {
	*x = ShortenRequest{}
	mi := &file_proto_shortugo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenRequest) ProtoMessage() {}

func (x *ShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenRequest.ProtoReflect.Descriptor instead.
func (*ShortenRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortugo_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *ShortenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ShortenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenResponse) Reset() {
	*x = ShortenResponse{}
	mi := &file_proto_shortugo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenResponse) ProtoMessage() {}

func (x *ShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenResponse.ProtoReflect.Descriptor instead.
func (*ShortenResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortugo_proto_rawDescGZIP(), []int{2}
}

func (x *ShortenResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type ExpandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrlId    string                 `protobuf:"bytes,1,opt,name=short_url_id,json=shortUrlId,proto3" json:"short_url_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandRequest) Reset() {
	*x = ExpandRequest{}
	mi := &file_proto_shortugo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandRequest) ProtoMessage() {}

func (x *ExpandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandRequest.ProtoReflect.Descriptor instead.
func (*ExpandRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortugo_proto_rawDescGZIP(), []int{3}
}

func (x *ExpandRequest) GetShortUrlId() string {
	if x != nil {
		return x.ShortUrlId
	}
	return ""
}

type ExpandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandResponse) Reset() {
	*x = ExpandResponse{}
	mi := &file_proto_shortugo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandResponse) ProtoMessage() {}

func (x *ExpandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandResponse.ProtoReflect.Descriptor instead.
func (*ExpandResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortugo_proto_rawDescGZIP(), []int{4}
}

func (x *ExpandResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type ShortenBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Urls          []*URLPair             `protobuf:"bytes,2,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchRequest) Reset() {
	*x = ShortenBatchRequest{}
	mi := &file_proto_shortugo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchRequest) ProtoMessage() {}

func (x *ShortenBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchRequest.ProtoReflect.Descriptor instead.
func (*ShortenBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortugo_proto_rawDescGZIP(), []int{5}
}

func (x *ShortenBatchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShortenBatchRequest) GetUrls() []*URLPair {
	if x != nil {
		return x.Urls
	}
	return nil
}

type ShortenBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*URLPair             `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchResponse) Reset() {
	*x = ShortenBatchResponse{}
	mi := &file_proto_shortugo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchResponse) ProtoMessage() {}

func (x *ShortenBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchResponse.ProtoReflect.Descriptor instead.
func (*ShortenBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortugo_proto_rawDescGZIP(), []int{6}
}

func (x *ShortenBatchResponse) GetResults() []*URLPair {
	if x != nil {
		return x.Results
	}
	return nil
}

type ListUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserURLsRequest) Reset() {
	*x = ListUserURLsRequest{}
	mi := &file_proto_shortugo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserURLsRequest) ProtoMessage() {}

func (x *ListUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserURLsRequest.ProtoReflect.Descriptor instead.
func (*ListUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortugo_proto_rawDescGZIP(), []int{7}
}

func (x *ListUserURLsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*URLPair             `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserURLsResponse) Reset() {
	*x = ListUserURLsResponse{}
	mi := &file_proto_shortugo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserURLsResponse) ProtoMessage() {}

func (x *ListUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserURLsResponse.ProtoReflect.Descriptor instead.
func (*ListUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortugo_proto_rawDescGZIP(), []int{8}
}

func (x *ListUserURLsResponse) GetUrls() []*URLPair {
	if x != nil {
		return x.Urls
	}
	return nil
}

type DeleteUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShortUrlIds   []string               `protobuf:"bytes,2,rep,name=short_url_ids,json=shortUrlIds,proto3" json:"short_url_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLsRequest) Reset() {
	*x = DeleteUserURLsRequest{}
	mi := &file_proto_shortugo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsRequest) ProtoMessage() {}

func (x *DeleteUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortugo_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteUserURLsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteUserURLsRequest) GetShortUrlIds() []string {
	if x != nil {
		return x.ShortUrlIds
	}
	return nil
}

type DeleteUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteUserURLsResponse) Reset() {
	*x = DeleteUserURLsResponse{}
	mi := &file_proto_shortugo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsResponse) ProtoMessage() {}

func (x *DeleteUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortugo_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteUserURLsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_shortugo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortugo_proto_rawDescGZIP(), []int{11}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_shortugo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortugo_proto_rawDescGZIP(), []int{12}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_shortugo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortugo_proto_rawDescGZIP(), []int{13}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_shortugo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortugo_proto_rawDescGZIP(), []int{14}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"` // IP address of the client, used for trusted subnet validation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_shortugo_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortugo_proto_rawDescGZIP(), []int{15}
}

func (x *StatsRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
	UrlCount      uint64 `protobuf:"varint,1,opt,name=url_count,json=urlCount,proto3" json:"url_count,omitempty"`
	UserCount     uint64 `protobuf:"varint,2,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_shortugo_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortugo_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortugo_proto_rawDescGZIP(), []int{16}
}

func (x *StatsResponse) GetUrlCount() uint64 {
	if x != nil {
		return x.UrlCount
	}
	return 0
}

func (x *StatsResponse) GetUserCount() uint64 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

var File_proto_shortugo_proto protoreflect.FileDescriptor

const file_proto_shortugo_proto_rawDesc = "" +
	"\n" +
	"\x14proto/shortugo.proto\x12\bshortugo\"p\n" +
	"\aURLPair\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\x12\x1b\n" +
	"\tshort_url\x18\x03 \x01(\tR\bshortUrl\"L\n" +
	"\x0eShortenRequest\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\".\n" +
	"\x0fShortenResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"1\n" +
	"\rExpandRequest\x12 \n" +
	"\fshort_url_id\x18\x01 \x01(\tR\n" +
	"shortUrlId\"3\n" +
	"\x0eExpandResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"U\n" +
	"\x13ShortenBatchRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x04urls\x18\x02 \x03(\v2\x11.shortugo.URLPairR\x04urls\"C\n" +
	"\x14ShortenBatchResponse\x12+\n" +
	"\aresults\x18\x01 \x03(\v2\x11.shortugo.URLPairR\aresults\".\n" +
	"\x13ListUserURLsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"=\n" +
	"\x14ListUserURLsResponse\x12%\n" +
	"\x04urls\x18\x01 \x03(\v2\x11.shortugo.URLPairR\x04urls\"T\n" +
	"\x15DeleteUserURLsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\"\n" +
	"\rshort_url_ids\x18\x02 \x03(\tR\vshortUrlIds\"2\n" +
	"\x16DeleteUserURLsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\r\n" +
	"\vPingRequest\"&\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x1e\n" +
	"\fStatsRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"K\n" +
	"\rStatsResponse\x12\x1b\n" +
	"\turl_count\x18\x01 \x01(\x04R\burlCount\x12\x1d\n" +
	"\n" +
	"user_count\x18\x02 \x01(\x04R\tuserCount2\xff\x04\n" +
	"\fURLShortener\x12>\n" +
	"\aShorten\x12\x18.shortugo.ShortenRequest\x1a\x19.shortugo.ShortenResponse\x12B\n" +
	"\vShortenJSON\x12\x18.shortugo.ShortenRequest\x1a\x19.shortugo.ShortenResponse\x12M\n" +
	"\fShortenBatch\x12\x1d.shortugo.ShortenBatchRequest\x1a\x1e.shortugo.ShortenBatchResponse\x12;\n" +
	"\x06Expand\x12\x17.shortugo.ExpandRequest\x1a\x18.shortugo.ExpandResponse\x12M\n" +
	"\fListUserURLs\x12\x1d.shortugo.ListUserURLsRequest\x1a\x1e.shortugo.ListUserURLsResponse\x12S\n" +
	"\x0eDeleteUserURLs\x12\x1f.shortugo.DeleteUserURLsRequest\x1a .shortugo.DeleteUserURLsResponse\x12J\n" +
	"\vHealthCheck\x12\x1c.shortugo.HealthCheckRequest\x1a\x1d.shortugo.HealthCheckResponse\x125\n" +
	"\x04Ping\x12\x15.shortugo.PingRequest\x1a\x16.shortugo.PingResponse\x128\n" +
	"\x05Stats\x12\x16.shortugo.StatsRequest\x1a\x17.shortugo.StatsResponseB\x0eZ\f/proto;protob\x06proto3"

var (
	file_proto_shortugo_proto_rawDescOnce sync.Once
	file_proto_shortugo_proto_rawDescData []byte
)

func file_proto_shortugo_proto_rawDescGZIP() []byte {
	file_proto_shortugo_proto_rawDescOnce.Do(func() {
		file_proto_shortugo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shortugo_proto_rawDesc), len(file_proto_shortugo_proto_rawDesc)))
	})
	return file_proto_shortugo_proto_rawDescData
}

var file_proto_shortugo_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_shortugo_proto_goTypes = []any{
	(*URLPair)(nil),                // 0: shortugo.URLPair
	(*ShortenRequest)(nil),         // 1: shortugo.ShortenRequest
	(*ShortenResponse)(nil),        // 2: shortugo.ShortenResponse
	(*ExpandRequest)(nil),          // 3: shortugo.ExpandRequest
	(*ExpandResponse)(nil),         // 4: shortugo.ExpandResponse
	(*ShortenBatchRequest)(nil),    // 5: shortugo.ShortenBatchRequest
	(*ShortenBatchResponse)(nil),   // 6: shortugo.ShortenBatchResponse
	(*ListUserURLsRequest)(nil),    // 7: shortugo.ListUserURLsRequest
	(*ListUserURLsResponse)(nil),   // 8: shortugo.ListUserURLsResponse
	(*DeleteUserURLsRequest)(nil),  // 9: shortugo.DeleteUserURLsRequest
	(*DeleteUserURLsResponse)(nil), // 10: shortugo.DeleteUserURLsResponse
	(*HealthCheckRequest)(nil),     // 11: shortugo.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 12: shortugo.HealthCheckResponse
	(*PingRequest)(nil),            // 13: shortugo.PingRequest
	(*PingResponse)(nil),           // 14: shortugo.PingResponse
	(*StatsRequest)(nil),           // 15: shortugo.StatsRequest
	(*StatsResponse)(nil),          // 16: shortugo.StatsResponse
}
var file_proto_shortugo_proto_depIdxs = []int32{
	0,  // 0: shortugo.ShortenBatchRequest.urls:type_name -> shortugo.URLPair
	0,  // 1: shortugo.ShortenBatchResponse.results:type_name -> shortugo.URLPair
	0,  // 2: shortugo.ListUserURLsResponse.urls:type_name -> shortugo.URLPair
	1,  // 3: shortugo.URLShortener.Shorten:input_type -> shortugo.ShortenRequest
	1,  // 4: shortugo.URLShortener.ShortenJSON:input_type -> shortugo.ShortenRequest
	5,  // 5: shortugo.URLShortener.ShortenBatch:input_type -> shortugo.ShortenBatchRequest
	3,  // 6: shortugo.URLShortener.Expand:input_type -> shortugo.ExpandRequest
	7,  // 7: shortugo.URLShortener.ListUserURLs:input_type -> shortugo.ListUserURLsRequest
	9,  // 8: shortugo.URLShortener.DeleteUserURLs:input_type -> shortugo.DeleteUserURLsRequest
	11, // 9: shortugo.URLShortener.HealthCheck:input_type -> shortugo.HealthCheckRequest
	13, // 10: shortugo.URLShortener.Ping:input_type -> shortugo.PingRequest
	15, // 11: shortugo.URLShortener.Stats:input_type -> shortugo.StatsRequest
	2,  // 12: shortugo.URLShortener.Shorten:output_type -> shortugo.ShortenResponse
	2,  // 13: shortugo.URLShortener.ShortenJSON:output_type -> shortugo.ShortenResponse
	6,  // 14: shortugo.URLShortener.ShortenBatch:output_type -> shortugo.ShortenBatchResponse
	4,  // 15: shortugo.URLShortener.Expand:output_type -> shortugo.ExpandResponse
	8,  // 16: shortugo.URLShortener.ListUserURLs:output_type -> shortugo.ListUserURLsResponse
	10, // 17: shortugo.URLShortener.DeleteUserURLs:output_type -> shortugo.DeleteUserURLsResponse
	12, // 18: shortugo.URLShortener.HealthCheck:output_type -> shortugo.HealthCheckResponse
	14, // 19: shortugo.URLShortener.Ping:output_type -> shortugo.PingResponse
	16, // 20: shortugo.URLShortener.Stats:output_type -> shortugo.StatsResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_shortugo_proto_init() }
func file_proto_shortugo_proto_init() {
	if File_proto_shortugo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shortugo_proto_rawDesc), len(file_proto_shortugo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shortugo_proto_goTypes,
		DependencyIndexes: file_proto_shortugo_proto_depIdxs,
		MessageInfos:      file_proto_shortugo_proto_msgTypes,
	}.Build()
	File_proto_shortugo_proto = out.File
	file_proto_shortugo_proto_goTypes = nil
	file_proto_shortugo_proto_depIdxs = nil
}
