name: multichecker

on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]

jobs:
  unittest:
    runs-on: ubuntu-latest
    container: golang:1.23

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -buildvcs=false -o staticlint ./cmd/staticlint

      - name: Run go vet with multichecker (filtered)
        run: |
          for pkg in $(go list ./...); do
            if [[ "$pkg" =~ mocks|main|noexit|multichecker|proto ]]; then
              echo "Skipping $pkg"
              continue
            fi
            go vet -vettool=$(pwd)/staticlint "$pkg"
          done

